# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: desc.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'desc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndesc.proto\x12\x08\x64\x65\x63ision\"/\n\x0c\x43heckRequest\x12\r\n\x05login\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\" \n\rCheckResponse\x12\x0f\n\x07\x61llowed\x18\x01 \x01(\x08\x32M\n\x0f\x44\x65\x63isionService\x12:\n\x05\x43heck\x12\x16.decision.CheckRequest\x1a\x17.decision.CheckResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'desc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHECKREQUEST']._serialized_start=24
  _globals['_CHECKREQUEST']._serialized_end=71
  _globals['_CHECKRESPONSE']._serialized_start=73
  _globals['_CHECKRESPONSE']._serialized_end=105
  _globals['_DECISIONSERVICE']._serialized_start=107
  _globals['_DECISIONSERVICE']._serialized_end=184
# @@protoc_insertion_point(module_scope)
